# Generated by Django 5.0.2 on 2024-02-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('date', models.CharField(blank=True, max_length=128)),
                ('lieu', models.CharField(blank=True, max_length=128)),
                ('participant', models.IntegerField(default=1)),
                ('description', models.TextField()),
            ],
        ),
    ]
