# Generated by Django 5.0.2 on 2024-02-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournois',
            name='image',
            field=models.FileField(blank=True, default='', max_length=250, upload_to='assets/imagestournoi/'),
        ),
    ]
