# Generated by Django 5.0.2 on 2024-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_tournois_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournois',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
