# Generated by Django 5.0.2 on 2024-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('date', models.CharField(blank=True, max_length=128)),
                ('heureDebut', models.CharField(blank=True, max_length=128)),
                ('heureFin', models.CharField(blank=True, max_length=128)),
                ('lieu', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, default='', max_length=250, upload_to='assets/imagesinformation/')),
            ],
        ),
    ]
