# Generated by Django 5.0.2 on 2024-02-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.FileField(blank=True, default='', max_length=250, upload_to='assets/imagesevenement/'),
        ),
    ]
