# Generated by Django 5.0.2 on 2024-02-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('image', models.FileField(blank=True, default='', max_length=250, upload_to='assets/imagesemissions/')),
                ('video', models.FileField(blank=True, default='', max_length=250, upload_to='assets/videoemissions/')),
                ('audio', models.FileField(blank=True, default='', max_length=250, upload_to='assets/audioemissions/')),
            ],
        ),
    ]
