# Generated by Django 5.0.2 on 2024-02-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.FileField(blank=True, default='', max_length=250, upload_to='assets/imagesinformation/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='titre',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
